name: passenger
description: A Flutter passenger application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State & Navigation
  provider: ^6.1.1
  go_router: ^12.1.3
  # HTTP & Storage
  http: ^1.1.2
  shared_preferences: ^2.2.2
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  # QR & Real-time
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6  # Replace qr_code_scanner with this
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^2.4.0
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.1.0
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.1
flutter_test:
    sdk: flutter
dev_dependencies:
    flutter_test:
      sdk: flutter
