dependencies:
  flutter:
    sdk: flutter
  # State & Navigation
  provider: ^6.1.1
  go_router: ^12.1.3
  # HTTP & Storage
  http: ^1.1.2
  shared_preferences: ^2.2.2
  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  # QR & Real-time
  qr_flutter: ^4.1.0
  socket_io_client: ^2.0.3+1
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2